"""Add image_url to CookingLog

Revision ID: 0fdefdf0b6f9
Revises: bb86e118a3e8
Create Date: 2025-05-15 05:28:39.809387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdefdf0b6f9'
down_revision = 'bb86e118a3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooking_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooking_log', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
