"""added whitelisted user ids in recipe table

Revision ID: 26a2b13cf961
Revises: 825e35092fb6
Create Date: 2025-05-04 21:42:22.438465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a2b13cf961'
down_revision = '825e35092fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whitelist', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('whitelist')

    # ### end Alembic commands ###
